version: '3.9'

services:
  app:
    container_name: workshop-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3434:3000"
    volumes:
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    restart: always
